---
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

- name: Set up development pre-reqs on a local machine
  hosts: dev
  become: yes

  tasks:
    - name: Make sure (empty) local repo structure exists
      become: no
      file: state=directory path=~/endaga-packages/dists/localdev/main/binary-amd64/

    - name: Make sure (empty) local repo Packages file exists
      become: no
      file: state=touch path=~/endaga-packages/dists/localdev/main/binary-amd64/Packages
      register: touch_log
      changed_when: touch_log.diff.before.state != "file"

    - import_tasks: base.yml

    - import_tasks: osmocom.yml

    - name: Add local repo (for local development)
      apt_repository:
        repo: 'deb [trusted=yes] file:/home/vagrant/endaga-packages localdev main'
        state: present
        filename: 10_file_home_vagrant_etagecom_packages
        update_cache: no

    - name: Set the version preferences
      copy: src=files/endaga-preferences dest=/etc/apt/preferences.d/endaga-preferences


    - name: Install prereqs for FPM
      apt: pkg={{ item }} state=present update_cache=no
      with_items:
          - ruby-dev
          - build-essential
          - libssl-dev

    - name: Setup FPM so we can build packages
      shell: gem install fpm

    - name: Setup build requirements for python packages
      apt: pkg={{ item }} state=present update_cache=no
      with_items:
          - python3-dev

    - name: Get pip3 installer (not from debian8 repositories, uses ancient version)
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install pip
      command: python3 /tmp/get-pip.py

    - name: Upgrade pip
      pip:
        name: pip
        state: latest

    - name: Install python dependencies from pypi via pip
      pip: name={{ item }} state=latest
      with_items:
          - babel
          - setuptools

    - name: Setup requirements for building FS from source (needed to generate working python modules)
      apt: pkg={{ item }} state=present update_cache=no
      with_items:
          - libsqlite3-dev
          - devscripts
          - libsmpp34-dev
          - libesl-perl
          - autoconf

    - name: Setup requirements for building psycopg2 from source
      apt: pkg=libpq-dev state=present update_cache=no

    - name: Setup requirements for building osmo-trx-uhd from source
      apt: pkg={{ item }} state=present update_cache=no
      with_items:
          - libusb-1.0-0-dev
          - libboost-dev
          - libtool
          - pkg-config
          - libosmocore
          - libosmocore-dev
          - git

